"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
[](bg:color_nord1 fg:color_nord0)\
$directory\
[](bg:color_nord2 fg:color_nord1)\
$git_branch\
$git_status\
[](bg:color_nord8 fg:color_nord2)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](bg:color_nord9 fg:color_nord8)\
$docker_context\
$conda\
[](bg:color_nord10 fg:color_nord9)\
$time\
[](fg:color_nord10)\
$line_break$character"""

command_timeout = 5000
# add_newline = false
palette = 'nord'

[palettes.nord]
# polar night
#color_nord0 = '#2e3440'
color_nord0 = '#282c34' # onehalf dark background
color_nord1 = '#3b4252'
color_nord2 = '#434c5e'
color_nord3 = '#4c566a'
# snow storm
color_nord4 = '#d8dee9'
color_nord5 = 'e5e9f0'
color_nord6 = '#eceff4'
# frost
color_nord7 = '#8fbcbb'
color_nord8 = '#88c0d0'
color_nord9 = '#81a1c1'
color_nord10 = '#5e81ac'
# aurora
color_nord11 = '#bf616a'
color_nord12 = '#d08770'
color_nord13 = '#ebcb8b'
color_nord14 = '#a3be8c'
color_nord15 = '#b48ead'

[aws]
symbol = ''

[buf]
symbol = ''

[c]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[character]
disabled = false
success_symbol = '[ ❱](bold fg:color_nord14)'
error_symbol = '[ ❱](bold fg:color_nord11)'
vimcmd_symbol = '[ ❰](bold fg:color_nord14)'
vimcmd_replace_one_symbol = '[ ❰](bold fg:color_nord15)'
vimcmd_replace_symbol = '[ ❰](bold fg:color_nord15)'
vimcmd_visual_symbol = '[ ❰](bold fg:color_nord13)'

[conda]
symbol = ''
style = 'bg:color_nord9'
format = '[[ $symbol( $environment) ](bg:color_nord9 fg:color_nord6)]($style)'

[crystal]
symbol = ''

[dart]
symbol = ''

[directory]
style = 'bold bg:color_nord1 fg:color_nord9'
format = '[ $path ]($style)'
truncation_length = 10
truncate_to_repo = false
truncation_symbol = '…/'
read_only = ' 󰌾'

[directory.substitutions]
"Documents" = '󰈙 '
"Downloads" = ' '
"Music" = '󰝚 '
"Pictures" = ' '
"Developer" = '󰲋 '

[docker_context]
symbol = ''
style = 'bg:color_nord9'
format = '[[ $symbol( $context) ](bg:color_nord9 fg:color_nord6)]($style)'

[elixir]
symbol = ''
style = 'bg:color_nord8'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ''
style = 'bg:color_nord8'
format = '[ $symbol ($version) ]($style)'

[fennel]
symbol = ''

[fossil_branch]
symbol = ''

[git_branch]
symbol = ''
style = 'bg:color_nord2'
format = '[[ $symbol $branch ](bg:color_nord2 fg:color_nord6)]($style)'

[git_status]
style = 'bg:color_nord2'
up_to_date = '[✔](bold bg:color_nord2 fg:color_nord14)'
modified = '[! ](bold bg:color_nord2 fg:color_nord11)'
conflicted = '[=${count} ](bold bg:color_nord2 fg:color_nord11)'
ahead = '[⇡${count} ](bold bg:color_nord2 fg:color_nord13)'
behind = '[⇣${count} ](bold bg:color_nord2 fg:color_nord13)'
diverged = '[⇕ ⇡${ahead_count} ⇣${behind_count} ](bold bg:color_nord2 fg:color_nord12)'
untracked = '[?${count} ](bold bg:color_nord2 fg:color_nord12)'
stashed = '[$${count} ](bg:color_nord2 fg:color_nord6)'
renamed = '[»${count} ](bold bg:color_nord2 fg:color_nord12)'
deleted = '[✘${count} ](bold bg:color_nord2 fg:color_nord11)'
staged = '[+${count} ](bold bg:color_nord2 fg:color_nord13)'
format = '[($all_status$ahead_behind) ](bg:color_nord2 fg:color_nord6)($style)'

[golang]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[guix_shell]
symbol = ''

[haskell]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[haxe]
symbol = ''

[hg_branch]
symbol = ''

[hostname]
ssh_symbol = ''
ssh_only = true
style = 'bg:color_nord0'
format = '[@ [$hostname](bg:color_nord0 fg:color_nord14) ]($style)'
trim_at = '.'

[java]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[julia]
symbol = ''
style = 'bg:color_nord8'
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[line_break]
disabled = false

[lua]
symbol = ''

[memory_usage]
symbol = '󰍛'

[meson]
symbol = '󰔷'

[nim]
symbol = '󰆥'
style = 'bg:color_nord8'
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = ''

[nodejs]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[ocaml]
symbol = ''

[os]
disabled = false
style = 'bg:color_nord0 fg:color_nord6'
format = '[ $symbol]($style)'

[os.symbols]
Alpaquita = ''
Alpine = ''
#AlmaLinux = ''
Amazon = ''
Android = ''
Arch = ''
Artix = ''
CentOS = ''
Debian = ''
DragonFly = ''
Emscripten = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = '󰛓'
Gentoo = ''
HardenedBSD = '󰞌'
Illumos = '󰈸'
#Kali = ''
Linux = ''
Mabox = ''
Macos = ''
Manjaro = ''
Mariner = ''
MidnightBSD = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = '󰈺'
openSUSE = ''
OracleLinux = '󰌷'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
#RockyLinux = ''
Redox = '󰀘'
Solus = '󰠳'
SUSE = ''
Ubuntu = ''
Unknown = ''
#Void = ''
Windows = '󰍲'

[package]
symbol = '󰏗'

[perl]
symbol = ''

[php]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[pijul_channel]
symbol = ''

[python]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[rlang]
symbol = '󰟔'

[ruby]
symbol = ''

[rust]
symbol = ''
style = 'bg:color_nord8'
format = '[[ $symbol( $version) ](bg:color_nord8 fg:color_nord6)]($style)'

[scala]
symbol = ''

[swift]
symbol = ''

[time]
disabled = false
time_format = '%R'
style = 'bg:color_nord10'
format = '[[  $time ](bg:color_nord10 fg:color_nord6)]($style)'

[username]
show_always = true
style_user = 'bg:color_nord0 fg:color_nord13'
style_root = 'bg:color_nord0 fg:color_nord13'
format = '[ $user ]($style)'

[zig]
symbol = ''
